services:
  - type: web
    name: batimemoire
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_URL
        value: https://ignara.xyz
      - key: STORAGE_ROOT
        value: /opt/render/project/src/storage
      - key: DATABASE_URL
        sync: false
    disk:
      name: batimemoire-data
      mountPath: /opt/render/project/src/storage
      sizeGB: 1
